### ISSUE TITLE
Thanks for this great idea!

### ISSUE THREAD

**Issue by juanfal** [fulldecent/corelocationcli#11]
I've needed to pick the swift files and build a new project, as it needs to be correctly signed.

Couldn't it be done with swift, perhaps, but through the command line?

**Comment by fulldecent** [comment]
Same thing in #12 with some details.

I am not aware of any way to publish needs-to-be-signed code through Homebrew. Have you seen anyone else do this before?

**Comment by ilovezfs** [comment]
@fulldecent no, Homebrew does not have its own signing certificates (and even if we were to have them, we wouldn't use them to sign third-party software). Nor does Homebrew Core distribute binaries provided by upstream. All of the binary bottles are built by us from source.

However, we do offer an alternative, which is called "Homebrew Cask," the code for which was recently absorbed into Homebrew itself. Cask is used for pre-built binaries, which may be signed by upstream. Typically Cask distributes GUI apps, but can be used for any binary distribution that cannot be built by downstream from source for a variety of reasons. So if signing is now an absolute requirement, you may want to consider transitioning your Homebrew distribution to Homebrew Cask distribution. The main repository for the actual cask files is https://github.com/caskroom/homebrew-cask

Note that typically, though, it's possible to configure the upstream software not to need signing. For example, we distribute LLVM, which requires signing for lldb, so that component is not provided by default, but users can build from source themselves if they want lldb and can sign it themselves. The rest of LLVM doesn't need to be signed, so we're able to distribute that, including clang.

**Comment by fulldecent** [comment]
God, Apple keeps make releasing harder and harder. This used to work fine and we could release through Homebrew. And that is the preferred route. Today's XKCD http://xkcd.com/1742/ is very relevant here.

But if we need to do binaries, I can consider that too.

**Comment by fulldecent** [comment]
We made a big change and moved this to Homebrew. Should be fixed now from https://github.com/caskroom/homebrew-cask/pull/31827

See updated README.
